name:                direct-json
version:             0.0.0.0
license:             BSD3
author:              "Kristiyan Tsaklev"
maintainer:          "cuki@cukii.me"
copyright:           "2020 Kristiyan Tsaklev"

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Widentities
- -Wincomplete-record-updates

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - bytestring
  - scientific
  - binary

tests:
  direct-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - direct-json
    - hspec
    - scientific
